# Dockerfile has three Arguments: tag 
# tag - tag for base mage (default: stable-slim)
#
# To build the image:
# $ docker build -t <dockerhub_user>/<dockerhub_repo> --build-arg arg=value .
# or using default args:
# $ docker build -t <dockerhub_user>/<dockerhub_repo> .

# set the tag (e.g. 23.0.3, 23.0, 23, latest : for erlang)
ARG tag=23.0

# Build image, e.g. erlang:23.0
FROM erlang:${tag}

# Which user and group to use 
ARG user=application
ARG group=standard

# Set environments
ENV LANG C.UTF-8

# Install system updates and tools
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
# Install system updates and tools
        ca-certificates \
        git && \
# Clean up & back to dialog front end
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*
ENV DEBIAN_FRONTEND=dialog

# Ports to expose
EXPOSE 8080

# Change user context and drop root privileges
RUN groupadd -r ${group} && \
    useradd --no-log-init -r -m -g ${group} ${user}
USER ${user}

