#!/usr/bin/env python3
"""
Main function description - To show in command help
"""
import sys
import argparse
import logging

from cicd import module_template


def cmdline_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)

    p.add_argument("non_required_int", nargs='?', type=int,
                   help="non_required_int description")
    p.add_argument("-v", "--verbosity", type=str, default='ERROR',
                   choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'], 
                   help="Sets the logging level (default: %(default)s)")

    group1 = p.add_mutually_exclusive_group(required=False)
    group1.add_argument('--enable', action="store_true")
    group1.add_argument('--disable', action="store_false")

    return(p.parse_args())


if __name__ == '__main__':
    # Set command line arguments
    args = cmdline_args()

    # Set logging level
    logging.basicConfig(level=getattr(logging, args.verbosity),
                        format='%(asctime)s - %(levelname)-8s - %(message)s')

    # Main module call
    logging.info("Starting hello_world with: '%s'", args)
    module_template.hello_world(args, **vars(args))
